/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComingSoonSlugRouteImport } from './routes/coming-soon/$slug'
import { Route as BrowseSlugRouteImport } from './routes/browse/$slug'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonSlugRoute = ComingSoonSlugRouteImport.update({
  id: '/coming-soon/$slug',
  path: '/coming-soon/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseSlugRoute = BrowseSlugRouteImport.update({
  id: '/browse/$slug',
  path: '/browse/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/browse/$slug': typeof BrowseSlugRoute
  '/coming-soon/$slug': typeof ComingSoonSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/browse/$slug': typeof BrowseSlugRoute
  '/coming-soon/$slug': typeof ComingSoonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/browse/$slug': typeof BrowseSlugRoute
  '/coming-soon/$slug': typeof ComingSoonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/browse/$slug'
    | '/coming-soon/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/contact' | '/browse/$slug' | '/coming-soon/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/browse/$slug'
    | '/coming-soon/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  BrowseSlugRoute: typeof BrowseSlugRoute
  ComingSoonSlugRoute: typeof ComingSoonSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon/$slug': {
      id: '/coming-soon/$slug'
      path: '/coming-soon/$slug'
      fullPath: '/coming-soon/$slug'
      preLoaderRoute: typeof ComingSoonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$slug': {
      id: '/browse/$slug'
      path: '/browse/$slug'
      fullPath: '/browse/$slug'
      preLoaderRoute: typeof BrowseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  BrowseSlugRoute: BrowseSlugRoute,
  ComingSoonSlugRoute: ComingSoonSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
